[build]
publish = "out/"
command = "npm run build"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[dev]
command = "npm run watch"
framework = '#static'

[context.dev.environment]
NODE_VERSION = "22.8.0"

[context.deploy-preview.environment]
NODE_VERSION = "22.8.0"

[context.production.environment]
NODE_VERSION = "22.8.0"
NODE_ENV = "production"

[[edge_functions]]
path = "/.well-known/webfinger"
function = "webfinger-redirect"

[[edge_functions]]
path = "/media/*"
function = "media-proxy"
cache = "manual"

[[headers]]
for = "/public.asc"

[headers.values]
Content-Type = "application/pgp-keys"

[[headers]]
for = "/feed"

[headers.values]
Content-Type = "application/rss+xml"

[[headers]]
for = "/feed.xml"

[headers.values]
Content-Type = "application/rss+xml"

[[headers]]
for = "/feed.rss"

[headers.values]
Content-Type = "application/rss+xml"

[[headers]]
for = "/feed.atom"

[headers.values]
Content-Type = "application/atom+xml"

[[headers]]
for = "/atom.xml"

[headers.values]
Content-Type = "application/atom+xml"

[[headers]]
for = "/feed.json"

[headers.values]
Content-Type = "application/json"

[[redirects]]
from = "https://www.bitch.lgbt/*"
to = "https://www.phoebe.codes/:splat"
status = 302
force = true

[[redirects]]
from = "/media/*"
to = "https://phoebecodes-personal-site-assets.s3.us-east-005.backblazeb2.com/:splat"
status = 200

[[redirects]]
from = "https://bitch.lgbt/*"
to = "https://www.phoebe.codes/:splat"
status = 302
force = true

[[redirects]]
from = "https://www.anarchist.nyc/*"
to = "https://www.phoebe.codes/:splat"
status = 302
force = true

[[redirects]]
from = "https://anarchist.nyc/*"
to = "https://www.phoebe.codes/:splat"
status = 302
force = true

[[redirects]]
from = "https://phoebeclarke.com/*"
to = "https://www.phoebeclarke.com/:splat"
status = 302
force = true

[[redirects]]
from = "/license"
to = "/license.txt"

[[redirects]]
from = "/LICENSE"
to = "/license.txt"

[[redirects]]
from = "/commit"
to = "/commit.txt"

[[redirects]]
from = "/COMMIT"
to = "/commit.txt"

[[redirects]]
from = "/blog"
to = "/blog/toc/1"

[[redirects]]
from = "/blog/toc"
to = "/blog/toc/1"

[[redirects]]
from = "/gallery"
to = "/gallery/1"

[[redirects]]
from = "/blog/posts/2023-05-28-12-00-00-blocking-hacker-news"
to = "/blog/posts/2023-05-28-blocking-hacker-news"

[[redirects]]
from = "/feed"
to = "/feed.rss"
status = 200

[[redirects]]
from = "/feed.xml"
to = "/feed.rss"
status = 200

[[redirects]]
from = "/atom.xml"
to = "/feed.atom"
status = 200
