---
name: build and deploy

on:
  push:
    branches:
      - main
      - astro

env:
  REGISTRY: rg.fr-par.scw.cloud/phoebecodes

jobs:
  push-to-registry:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=astro
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}:buildcache
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}:buildcache

  redeploy-stack:
    runs-on: ubuntu-latest
    needs: push-to-registry

    steps:
      - uses: scaleway/action-scw@v0
        with:
          save-config: true
          export-config: true
          version: v2.38.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      - uses: scaleway/action-scw@v0
        with:
          args: container container deploy 49f1c1c9-f23c-4f0c-bc05-036ac147160e
